pipelines:
  "zoo-application":
    group: "simple-app"
    materials:
      git:
        git: "https://github.com/tobivogel/zoo-application.git"
    stages:
      - build:
          jobs:
            build:
              clean_workspace: true
              artifacts:
                - build:
                   source: build/libs/*.jar
                   destination: build/libs
                - test:
                   source: "build/test-results/test/*.xml"
                   destination: testoutput
              tasks:
                - exec:
                   command: ".gradlew"
                   arguments:
                    - build
